In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"


In [3]:
headernames = ['sepal-length','sepal-width','petal-length','petal-width','Class']

In [4]:
dataset = pd.read_csv(path, names = headernames)
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [17]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,4].values
print(y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x,y, test_size = 0.30)

In [18]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100) #n_estimators is no of trees
classifier.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [8]:
y_pred = classifier.predict(x_test)

In [9]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classfifcation Report:")
print(result1)
result2 = accuracy_score(y_test, y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[14  0  0]
 [ 0 13  2]
 [ 0  0 16]]
Classfifcation Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       1.00      0.87      0.93        15
 Iris-virginica       0.89      1.00      0.94        16

       accuracy                           0.96        45
      macro avg       0.96      0.96      0.96        45
   weighted avg       0.96      0.96      0.96        45

Accuracy: 0.9555555555555556


In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [20]:
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/ecoli/ecoli.data"

In [25]:
dataset = pd.read_csv(path)
print(dataset)

    AAT_ECOLI   0.49  0.29  0.48  0.50  0.56  0.24  0.35   cp
0    ACEA_ECOLI  0.07  0.40  0.48  0.50  0.54  0.35...       
1    ACEK_ECOLI  0.56  0.40  0.48  0.50  0.49  0.37...       
2    ACKA_ECOLI  0.59  0.49  0.48  0.50  0.52  0.45...       
3    ADI_ECOLI   0.23  0.32  0.48  0.50  0.55  0.25...       
4    ALKH_ECOLI  0.67  0.39  0.48  0.50  0.36  0.38...       
..                                                 ...       
330  TREA_ECOLI  0.74  0.56  0.48  0.50  0.47  0.68...       
331  UGPB_ECOLI  0.71  0.57  0.48  0.50  0.48  0.35...       
332  USHA_ECOLI  0.61  0.60  0.48  0.50  0.44  0.39...       
333  XYLF_ECOLI  0.59  0.61  0.48  0.50  0.42  0.42...       
334  YTFQ_ECOLI  0.74  0.74  0.48  0.50  0.31  0.53...       

[335 rows x 1 columns]
